In [1]:
import numpy as np

In [4]:
n = np.random.randn(30)

In [5]:
n

array([ 1.84596264, -0.55813833, -1.01498772, -1.75469304,  1.68407604,
       -1.19500276,  0.53517695, -1.91711117,  0.12094332, -1.12938342,
        1.25166407,  0.57207474,  0.80019257,  0.22239288,  1.05507251,
        0.80035726,  0.06689196, -0.42307757, -0.67419097, -0.04606622,
       -1.60634031,  0.41366576, -0.16385573,  1.1343548 , -0.59291227,
        0.46370336,  0.53253475,  0.076045  , -1.00040439,  0.18732828])

In [6]:
np.max(n) - np.min(n)

3.763073808665406

In [8]:
#inter quartile range needs to be find
#25% 50% 75%
#q1 q2 q3

In [9]:
q1 = np.percentile(n,25)   #quartile 1

In [10]:
q2 = np.percentile(n,50)   #quartile 2

In [11]:
q3 = np.percentile(n,75)   #quartile 3

In [12]:
#inter quartile range
iqr = q3-q1

In [13]:
#variance
#how far data is away from the mean

In [14]:
population = np.random.randn(100)

In [16]:
population

array([-0.78944799, -0.33777599,  0.30241092, -0.76050254,  0.58007353,
        1.96502327,  1.44400628,  0.98875706,  0.26286311,  1.11066678,
        0.31210785,  0.11091867,  0.05562595,  1.5897745 , -1.39161119,
        1.10786445, -1.65048919,  0.06283076,  0.41916773, -0.11326962,
        1.58596964, -1.14883099, -1.29293757,  1.00677623,  1.12821124,
       -0.09232969,  0.71662845,  0.44804451, -1.40825107, -0.15471231,
        2.48141085,  0.23883485,  1.52234735, -0.06111784, -1.44573157,
        0.98790955, -1.06932716, -0.62511901,  0.17072371, -0.77024615,
        2.90608052,  0.86024071,  0.12060476,  0.65598495,  1.75122922,
        0.39834174, -0.43163428,  1.0954645 , -0.28434313,  0.63081275,
        0.54979314, -0.37525612,  0.9463771 ,  1.46689627, -0.0708298 ,
       -0.10675307,  0.77616084, -0.3858383 ,  0.82046827,  0.27385951,
       -0.353271  , -0.32734139, -0.39553028,  0.31935825,  0.94279621,
        0.75988254, -0.34472287,  1.05963899,  0.46329345, -1.59

In [17]:
sample = np.random.choice(population, 30)
sample

array([-1.10480915,  0.58007353,  0.17072371,  0.46329345, -1.44573157,
        1.31560641,  0.30241092, -0.32734139,  0.77616084,  2.48141085,
       -0.33777599, -0.11326962,  0.29375282,  1.12821124, -0.39553028,
       -0.43163428,  1.39116717, -0.12122448, -0.43589998,  0.65598495,
       -0.353271  ,  1.75122922,  1.03653619,  1.52234735, -0.43589998,
       -0.76050254, -1.39161119,  1.05963899,  0.65598495,  0.39834174])

In [18]:
np.var(population)    #to find variance

0.9540694320161636

In [19]:
np.var(sample)

0.8555911286381176

In [21]:
# to find std deviation
#std deviation gives more exact values as to how far data is from the mean

In [22]:
np.std(population)

0.9767647782430341

In [24]:
np.std(sample)

0.924981690974539