In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
m=np.random.randint(7,10,20)

In [19]:
print(m)

[9 7 8 8 9 9 7 9 8 9 9 9 8 8 9 8 8 8 9 9]


In [20]:
np.mean(m)     #mean

8.4

In [21]:
 np.median(m)    #median

8.5

In [22]:
import statistics as stats   # import statistics in order to find mode

In [23]:
stats.mode(m)     #mode

9

In [24]:
population = np.random.randint(10,20,100)

In [25]:
population

array([16, 13, 14, 19, 10, 18, 12, 15, 19, 17, 19, 11, 15, 19, 16, 17, 14,
       18, 10, 13, 13, 19, 10, 18, 14, 13, 11, 17, 14, 16, 10, 18, 16, 17,
       17, 14, 12, 16, 11, 12, 16, 18, 16, 13, 18, 17, 10, 13, 12, 17, 16,
       18, 10, 17, 19, 14, 16, 14, 18, 17, 18, 19, 11, 11, 14, 16, 17, 17,
       14, 13, 16, 13, 17, 14, 10, 13, 10, 17, 12, 11, 18, 13, 14, 13, 15,
       16, 12, 13, 10, 10, 15, 12, 19, 14, 10, 13, 13, 12, 19, 15])

In [26]:
np.mean(population)

14.61

In [27]:
np.median(population)

14.0

In [28]:
mode(population)

13

In [29]:
sample = np.random.choice(population, 20)

In [30]:
sample

array([12, 16, 18, 19, 16, 12, 10, 13, 10, 11, 12, 10, 19, 19, 13, 10, 11,
       10, 14, 12])

In [31]:
np.mean(sample)

13.35

In [32]:
np.median(sample)

12.0

In [33]:
stats.mode(sample)

10

In [34]:
sample_1 = np.random.choice(population, 15)
sample_2 = np.random.choice(population, 15)
sample_3 = np.random.choice(population, 15)
sample_4 = np.random.choice(population, 15)

In [36]:
all_samples = [sample,sample_1,sample_2,sample_3,sample_4]

In [38]:
sample_mean = []

for i in all_samples:
    sample_mean.append(np.mean(i))
    
sample_mean

[13.35, 14.8, 13.666666666666666, 14.533333333333333, 14.666666666666666]

In [39]:
np.mean(sample_mean)             #mean of sampling distribution

14.203333333333333

In [40]:
np.mean(population)         #mean of sampling distribution is almost equal to population mean

14.61